name = "RedstoneToolkit"
author = "Scorpio"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "783ead4f2f8a55a9aa80f2a33ad30c14b6b6c01aa6b7c7cbea14ec19df173049"

[versions]
fabric = "0.18.6"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1-pre-1", "26.1-rc-2"]
