name = "RedstoneToolkit"
author = "Scorpio"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a23da92c427222d940a833e2fd16e35b2446a7b9b86155cf0b3c6682da0fcad"

[versions]
fabric = "0.18.4"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1-pre-1", "26.1-rc-2"]
