name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aee2e4e12738a0c6f83643f8ecde2aae724fbeda6293dfad520d7882bee5a4f3"

[versions]
fabric = "0.19.5"
minecraft = "1.19.4"
