name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb47999030853710b46d09a56a848128492b298bcc15016ab8e7d4c71827f211"

[versions]
fabric = "0.19.3"
minecraft = "1.19.4"
