name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86037adf49673ea2e98541db2a863d2ecb6ae363d38543bfba4b6567f02a964a"

[versions]
fabric = "0.19.3"
minecraft = "1.20.6"
