name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcb74bef3f82f2693c2d58ae27c745a6364d52fa7063ad0f249cec3644f6254f"

[versions]
fabric = "0.19.3"
minecraft = "1.20.6"
