name = "RedstoneToolkit"
author = "Scorpio"
version = "0.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "106ca92f4369a83bcec305b0ad8dbb24cb43e7eef7840759cbeaeed9c93b3883"

[versions]
fabric = "0.18.6"
minecraft = "26.1.1"

[options]
acceptable-game-versions = ["26.1"]
