name = "RedstoneToolkit"
author = "Scorpio"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b2bcd2d75be3b661030f768b626dfd31df69ffe676fa0a76ff1808d1f5aa36f"

[versions]
fabric = "0.18.6"
minecraft = "26.1.1"
