name = "RedstoneToolkit"
author = "Scorpio"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9e61c46392a3b6c1a3234efaeab02e9e6827462d1a77c13cbac7cce63b9e970"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
