name = "RedstoneToolkit"
author = "Scorpio"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b233a2bc59e6146e6719f58769a57d8eaaf54ff03eb1ead43798af310d8fa88f"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
