name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f49ae4213138237f595729722908e65943049da7d96be80b0fc4777b8229bc0"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
