name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68e64c124f8170926fb1c4e9c69675b9ed2c0abf28d6570704aa2f4c3794d481"

[versions]
fabric = "0.18.4"
minecraft = "1.17.1"
