name = "RedstoneToolkit"
author = "Scorpio"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1299885d7fe7af66d8641cb5939e5850170d619554648feb08d0ec34e359561"

[versions]
fabric = "0.18.4"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1-pre-1", "26.1-rc-2"]
