name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a09e488fb8fc8a922005c64088113679b9d34893e65d9e37903d8902e6e03e3"

[versions]
fabric = "0.19.3"
minecraft = "1.17.1"
