name = "RedstoneToolkit"
author = "Scorpio"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "773da315b91d8303218675596be5ee3ced9d248cbcee7b69905096341d4c83b3"

[versions]
fabric = "0.18.4"
minecraft = "1.17.1"
