name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba9487178205963ea2ab1f9a5a9e3a0e6c6dda9b56a1067814f0048d28ad0673"

[versions]
fabric = "0.18.4"
minecraft = "26.1-snapshot-9"

[options]
acceptable-game-versions = ["26.1-snapshot-4", "26.1-snapshot-5", "26.1-snapshot-6", "26.1-snapshot-7", "26.1-snapshot-8"]
