name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "366387cca0bcfaf94d8ef99c79dba7e9cd490177ac58dedc29d968a24059c276"

[versions]
fabric = "0.19.5"
minecraft = "1.20.6"
