name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d2fbc31220f77f7daf963f24af1b35fd16018be1bfdbbcb2158e8d07df62e45"

[versions]
fabric = "0.18.4"
minecraft = "1.16.5"
