name = "RedstoneToolkit"
author = "Scorpio"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bdc55bee98e75ae27abc646da30f4dfa4dccbd8ed865ef7bbf0a3eaac8b718f"

[versions]
fabric = "0.18.4"
minecraft = "1.16.5"
