name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db07fb985424d73fb4eb1ee5b46ef711267939cefbbd9438742bf1d7acc642ff"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
