name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3b3f7d90838b0b0f88615e482a50295318773b2b07f411418c69cfafb6c750b"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
