name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d0b5a4d37bfa9bc9f9e007a1c11ed194d8f402cbadc9448a8ca4de7fdff2ba5"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
