name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3865aac4506ace572f6d1613f97e8310d0934d306d16e8eff0ca8cb8ddbe27b8"

[versions]
fabric = "0.19.5"
minecraft = "1.16.5"
