name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91ca878be9d537d62864f4e6df271eb915127e88256585f7d70341a8ac89b182"

[versions]
fabric = "0.19.5"
minecraft = "1.16.5"
