name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2641852ef43cdb21f625464a847bf0cce0971cc3fe3cb30fb956efae9d16bbc0"

[versions]
fabric = "0.19.3"
minecraft = "1.16.5"
