name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21a69dc66d427016ea568335d1c502a358dd378e052d5f2846ab726429e586b8"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
