name = "RedstoneToolkit"
author = "Scorpio"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "838d77365afc01e3a07e66a002c3b13ebfc0ff0012f39c3beea442824a01f257"

[versions]
fabric = "0.18.4"
minecraft = "1.18.2"
