name = "RedstoneToolkit"
author = "Scorpio"
version = "0.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7a7e043287d0e5e62e497352d69512a21b127b737e39261b7ceb268124a6c14"

[versions]
fabric = "0.18.6"
minecraft = "1.17.1"
