name = "RedstoneToolkit"
author = "Scorpio"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15ab86b147180b5abac9234ed9aaceb3e82697a6ed295474382c7be85f6c2934"

[versions]
fabric = "0.18.4"
minecraft = "1.17.1"
