name = "RedstoneToolkit"
author = "Scorpio"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b63efd0f34b87f8752f8e40464102918eeb49bf0309ccb6c690734c23ebd7891"

[versions]
fabric = "0.19.1"
minecraft = "1.17.1"
