name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f63c3929e149693f27dad8b4002dd9f5a47322d31d1262d83f45c80cee25e28"

[versions]
fabric = "0.18.4"
minecraft = "1.19.4"
