name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5fcf6a1f2826b27f01ded76be37fdd74e8d3eca4a0ae41e3fe8c17df7bba70c"

[versions]
fabric = "0.18.4"
minecraft = "1.19.4"
