name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96b78de160551a20406f47904961b79de0606ef179b3308f7c08ab81202e91f2"

[versions]
fabric = "0.19.3"
minecraft = "1.19.4"
