name = "RedstoneToolkit"
author = "Scorpio"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7445c41ad4b8f993af1071882ac67e0472b253d8c59ae23d2c90bc3c2c12f2f5"

[versions]
fabric = "0.18.6"
minecraft = "1.19.4"
