name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2eb77734c0e1dde03b86053190be98d02074e6fe4405a9c69ce7ee41b3857993"

[versions]
fabric = "0.19.1"
minecraft = "1.19.4"
