name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87519668eadbc5cfcf81161c35ca2baac86f7335ae618279eca432e48f911959"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
