name = "RedstoneToolkit"
author = "Scorpio"
version = "0.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82c52759232897959560c11bb292a138454023e0e650aba4087de0963eac121b"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
