name = "RedstoneToolkit"
author = "Scorpio"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2f89fe594f7d31e9da71b1717e2fcae0ee24545e1b1d6a3ae09741a7e3a4d1a"

[versions]
fabric = "0.19.1"
minecraft = "26.2-snapshot-2"

[options]
acceptable-game-versions = ["26.2-snapshot-1"]
