name = "RedstoneToolkit"
author = "Scorpio"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f98c5218c087e07934297c0c15dddcb13dab6646e98f49cd9e6a36d799acbc2b"

[versions]
fabric = "0.18.4"
minecraft = "1.18.2"
