name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e18eaf65d5a793e2d711e7eeb0ae72f00f3e053dacfb12cfc53ea2dc0cba72c3"

[versions]
fabric = "0.19.3"
minecraft = "1.18.2"
