name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bdb18c3778bc99a8524e9c266b5d6129c9c3af01f20d93d4ca5cc8de09e7071"

[versions]
fabric = "0.19.5"
minecraft = "1.18.2"
