name = "RedstoneToolkit"
author = "Scorpio"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7789721b1e89f8254d5bf1030dc212282416a7ec10054df4cfaa72d11886e99"

[versions]
fabric = "0.19.5"
minecraft = "26.3"

[options]
acceptable-game-versions = ["26.3-rc-3"]
