name = "RedstoneToolkit"
author = "Scorpio"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8230897ed8102d69136bf0e76d534256502a473c7aeea28680ebbfc19f5de69"

[versions]
fabric = "0.18.4"
minecraft = "1.18.2"
