name = "RedstoneToolkit"
author = "Scorpio"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f09c95471fa22a4008eb18833b9b35074dafd4e037503f1a7a54b72158f075b"

[versions]
fabric = "0.18.4"
minecraft = "1.18.2"
