name = "RedstoneToolkit"
author = "Scorpio"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab2bbf067f919daf57cc9b0caa2e1ef09978141d8e9d1753e0eb983a40398b99"

[versions]
fabric = "0.18.5"
minecraft = "1.18.2"
