name = "RedstoneToolkit"
author = "Scorpio"
version = "0.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fa11fcf3e05c44797a0a2dd3c19a3d1cc3beec53e10e71460416b722847aef5"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
