name = "RedstoneToolkit"
author = "Scorpio"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bc8fb4a1719cacdb3549344b959250da2965f0ec8c1b1d33d76501bf8b02f31"

[versions]
fabric = "0.18.6"
minecraft = "26.1.1"
