name = "RedstoneToolkit"
author = "Scorpio"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "560d90c1dba37a36265c1f6ba1958a785544d7c439c8390b6dafeb07996c136a"

[versions]
fabric = "0.18.6"
minecraft = "26.1.1"
