name = "RedstoneToolkit"
author = "Scorpio"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88d75cf47bae8dee448fc28640ed106983a532c1e1f1cb8cd049e2a46598d0c8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.6"
