name = "RedstoneToolkit"
author = "Scorpio"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dce2a7071ae7e26ab0774233ecf963b5b1db40c6635da1fd4456d64aac401e6"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
