name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05eac1d09c408138a2cde3d28a7bd2379110c66d1889655ac7eaeca30a1da0ee"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
