name = "RedstoneToolkit"
author = "Scorpio"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9edad1b2206f35f734e6722fb8fc18220590a28dede7702e9ae5fa71583acbb8"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
