name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d77efe6fb11e25177d7d2a86eb7558a5527040d98e59ec35ad157eab70ccd39"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
