name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14f28bcfcb9cc932e8e9c6526fa8c3ce86ffbf82dad57c07e97aa018dd19b6c0"

[versions]
fabric = "0.19.1"
minecraft = "1.21.11"
