name = "RedstoneToolkit"
author = "Scorpio"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a9468ff3ea4d9195c67e3df2a62211e3a43131556d7eb065681b78768e25fe1"

[versions]
fabric = "0.18.6"
minecraft = "1.21.11"
