name = "RedstoneToolkit"
author = "Scorpio"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50c6222da7697f68a8d155f7984ff86e456d0c8dc1e8618af9fd2cd2749f3163"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1"]
