name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71143cca678552494623f72b6917daac4e4dda13c12e74def63d26d8b9cf4587"

[versions]
fabric = "0.19.5"
minecraft = "26.3"

[options]
acceptable-game-versions = ["26.3-rc-3"]
