name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a61e311c2b2023a81c3e4eb3106af7a412b537ab05fccd60ccfae58152f2cf76"

[versions]
fabric = "0.19.3"
minecraft = "26.3-snapshot-2"
