name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aa451fff4a9f36c59c1f9fd65db4168331398c8c7e39d9478ddc53bba5fa4ff"

[versions]
fabric = "0.19.3"
minecraft = "26.3-snapshot-1"
