name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "862be49c6ab27e531900a8378647e688a99c902e349e4f035bbe1a3d0ada530b"

[versions]
fabric = "0.19.5"
minecraft = "1.16.5"
