name = "RedstoneToolkit"
author = "Scorpio"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd5e236b4921833dfd30666bf8805581f5b5a8440443d68a9de4f36a10ef2108"

[versions]
fabric = "0.18.6"
minecraft = "1.16.5"
