name = "RedstoneToolkit"
author = "Scorpio"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "795c4ab5644dad0c105ff7030e785ce09be3f6a36607735e71ed05e6967f8b8d"

[versions]
fabric = "0.18.4"
minecraft = "1.16.5"
