name = "RedstoneToolkit"
author = "Scorpio"
version = "0.13.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "764b0812169189710ba722a1f8d38bb891e3a66624ab8f02bcebe669784a77f4"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
