name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81a7c9c0ed070a914de4d6e13c9749fb5d36efe9c10005a54d3b7c7900d009d7"

[versions]
fabric = "0.19.5"
minecraft = "26.4-snapshot-2"
