name = "RedstoneToolkit"
author = "Scorpio"
version = "0.15.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed4c09d408b5249cde3bdda9dadd36d55b5b499ee7c47f0675ab02b39eacc8f7"

[versions]
fabric = "0.19.5"
minecraft = "26.4-snapshot-2"
