name: release
on: workflow_dispatch

jobs:
  find_matrix:
    runs-on: windows-latest
    # POWERSHELL CANNOT WRITE VARIABLES
    defaults:
      run:
        shell: bash
    outputs:
      json_str: ${{ steps.read-json.outputs.json_str }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: generate data
        run: 'python .github/workflows/script/matrix.py'
      - name: read json
        id: read-json
        run: |
          echo "json_str=$(cat matrix_data.json)" >> $GITHUB_OUTPUT

  modrinth_publish:
    runs-on: windows-latest
    needs: find_matrix
    # POWERSHELL CANNOT WRITE VARIABLES
    defaults:
      run:
        shell: bash
    env:
      IS_RELEASE: 'true'
      PLATFORM: 'modrinth'
    strategy:
      max-parallel: 1
      matrix:
        mc_ver: ${{ fromJSON(needs.find_matrix.outputs.json_str).modrinth.mc_vers }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: data
        id: data
        run: |
          echo "dir=${{ fromJSON(needs.find_matrix.outputs.json_str)[env.PLATFORM].dir_map[matrix.mc_ver] }}" >> $GITHUB_OUTPUT
          echo "ver=${{ fromJSON(needs.find_matrix.outputs.json_str)[env.PLATFORM].ver_map[matrix.mc_ver] }}" >> $GITHUB_OUTPUT
          echo "type=${{ fromJSON(needs.find_matrix.outputs.json_str)[env.PLATFORM].type_map[matrix.mc_ver] }}" >> $GITHUB_OUTPUT
      - name: get release info
        id: release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ format('release/{0}', steps.data.outputs.ver) }}
          doNotFailIfNotFound: true
      - name: check version
        id: check
        run: |
          python .github/workflows/script/check.py
          echo "json_str=$(cat publish_data.json)" >> $GITHUB_OUTPUT
        env:
          dir: ${{ steps.data.outputs.dir }}
          assets: ${{ steps.release.outputs.assets }}
      - name: get condition
        id: condition
        run: echo "publish=${{ fromJSON(steps.check.outputs.json_str).publish }}" >> $GITHUB_OUTPUT
      - name: pip requirements
        if: steps.condition.outputs.publish == 'true'
        run: pip install -r requirements.txt
      - name: export
        if: steps.condition.outputs.publish == 'true'
        run: ${{ format('python -m script export --platform {0} --version {1}', env.PLATFORM, steps.data.outputs.dir) }}
      - name: publish
        if: steps.condition.outputs.publish == 'true'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ccYQOriP
          modrinth-token: ${{ secrets.MR_TOKEN }}

          github-token: ${{ secrets.GH_TOKEN }}
          github-tag: ${{ format('release/{0}', steps.data.outputs.ver) }}

          name: ${{ format('Redstone Toolkit v{0}', steps.data.outputs.ver) }}
          files: export/*.(mrpack|zip)
          loaders: fabric
          version: ${{ format('{0}+mc{1}', steps.data.outputs.ver, matrix.mc_ver) }}
          version-type: ${{ steps.data.outputs.type }}
          game-versions: ${{ matrix.mc_ver }}
          changelog-file: changelog.md
          fail-mode: skip

  curseforge_publish:
    runs-on: windows-latest
    needs:
      - find_matrix
      - modrinth_publish
    # POWERSHELL CANNOT WRITE VARIABLES
    defaults:
      run:
        shell: bash
    env:
      IS_RELEASE: 'true'
      PLATFORM: 'curseforge'
    strategy:
      max-parallel: 1
      matrix:
        mc_ver: ${{ fromJSON(needs.find_matrix.outputs.json_str).curseforge.mc_vers }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: data
        id: data
        run: |
          echo "dir=${{ fromJSON(needs.find_matrix.outputs.json_str)[env.PLATFORM].dir_map[matrix.mc_ver] }}" >> $GITHUB_OUTPUT
          echo "ver=${{ fromJSON(needs.find_matrix.outputs.json_str)[env.PLATFORM].ver_map[matrix.mc_ver] }}" >> $GITHUB_OUTPUT
          echo "type=${{ fromJSON(needs.find_matrix.outputs.json_str)[env.PLATFORM].type_map[matrix.mc_ver] }}" >> $GITHUB_OUTPUT
      - name: get release info
        id: release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ format('release/{0}', steps.data.outputs.ver) }}
          doNotFailIfNotFound: true
      - name: check version
        id: check
        run: |
          python .github/workflows/script/check.py
          echo "json_str=$(cat publish_data.json)" >> $GITHUB_OUTPUT
        env:
          dir: ${{ steps.data.outputs.dir }}
          assets: ${{ steps.release.outputs.assets }}
      - name: get condition
        id: condition
        run: echo "publish=${{ fromJSON(steps.check.outputs.json_str).publish }}" >> $GITHUB_OUTPUT
      - name: pip requirements
        if: steps.condition.outputs.publish == 'true'
        run: pip install -r requirements.txt
      - name: export
        if: steps.condition.outputs.publish == 'true'
        run: ${{ format('python -m script export --platform {0} --version {1}', env.PLATFORM, steps.data.outputs.dir) }}
      - name: publish
        if: steps.condition.outputs.publish == 'true'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1449021
          curseforge-token: ${{ secrets.CF_TOKEN }}

          github-token: ${{ secrets.GH_TOKEN }}
          github-tag: ${{ format('release/{0}', steps.data.outputs.ver) }}

          name: ${{ format('Redstone Toolkit v{0}', steps.data.outputs.ver) }}
          files: export/*.(mrpack|zip)
          loaders: fabric
          version: ${{ format('{0}+mc{1}', steps.data.outputs.ver, matrix.mc_ver) }}
          version-type: ${{ steps.data.outputs.type }}
          game-versions: ${{ matrix.mc_ver }}
          changelog-file: changelog.md
          fail-mode: skip